version: '3.8'


services:
  webserver:
    image: zhuquelab/aig-server:latest
    container_name: ai-infra-guard-webserver
    ports:
      - "8088:8088"
    environment:
      - APP_ENV=production
      - UPLOAD_DIR=/app/uploads
      - DB_PATH=/app/db/tasks.db
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - ai-infra-guard-network
    restart: always
    healthcheck:
      test: [ "CMD", "curl",  "http://localhost:8088/" ]
      interval: 30s
      timeout: 3s
      retries: 3
  agent:
    image: zhuquelab/aig-agent:latest
    container_name: ai-infra-guard-agent
    environment:
      - TZ=Asia/Shanghai
      - AIG_SERVER=webserver:8088
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    networks:
      - ai-infra-guard-network
    restart: always
    depends_on:
      webserver:
        condition: service_healthy

networks:
  ai-infra-guard-network:
    driver: bridge
    name: ai-infra-guard-network